### ISSUE TITLE
Consider working together

### ISSUE THREAD

**Issue by mansona** [carsondarling/mongoose-jsonapi#1]
Hi there, 

I am the author of https://github.com/stonecircle/express-autoroute-json and I just came across your project. I recently got a request from someone to expose my mongoose jsonapi serializer as a npm module in its own right and I was wondering if it might be something that would meet your needs: https://github.com/stonecircle/express-autoroute-json/blob/master/lib/serialise.js

It has a bunch of extra features that aren't well documented at the moment but if you were potentially interested in collaborating we could discuss the external API and documentation 👍

**Comment by carsondarling** [comment]
Always open to collaboration! Reading through your serializer, initial thoughts are:

- I like the `selfReferences` option
- It appears that by default it treats any key that starts with an underscore as hidden, but doesn't let you override it if you wanted to specify that attribute explicitly
- You seem to have an implicit requirement that the options provides a Mongoose model

I'd be more than happy to take a look at any PR around documentation or additional features, especially since the documentation this module is definitely lacking.
